import SinglePosts from "@/components/Posts/SinglePosts";
import { getPostsTopPage } from "@/lib/notionAPI";
import { GetStaticPaths, GetStaticProps } from "next";
import Head from "next/head";

export const getStaticPaths: GetStaticPaths = async () => {
  return {
    paths: [{ params: { page: "1" } }, { params: { page: "2" } }],
    fallback: "blocking",
  };
};

export const getStaticProps: GetStaticProps = async () => {
  const topPosts = await getPostsTopPage(4);

  return {
    props: {
      topPosts,
    },
    revalidate: 60 * 60,
  };
};

const BlogPageList = ({ topPosts }) => {
  return (
    <div className="container h-full w-full mx-auto">
      <Head>
        <title>Notion Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container w-full mt-16">
        <h1 className="text-5xl font-medium mb-16 text-center">
          トップページです！
        </h1>
        {topPosts.map((post) => (
          <div className="mx-4" key={post.id}>
            <SinglePosts
              title={post.title}
              description={post.description}
              date={post.date}
              tags={post.tags}
              slug={post.slug}
            />
          </div>
        ))}
      </main>
    </div>
  );
};

export default BlogPageList;
