import { getAllPosts } from "@/lib/notionAPI";
import Head from "next/head";

export const getStaticProps = async () => {
  const allPosts = await getAllPosts();
  console.log("posts:", allPosts)
  return {
    props: {
      allPosts,
    },
    revalidate: 60 * 60,
  };
};

export default function Home({ allPosts }) {
  console.log("home: ", allPosts);
  // console.debug("こんにちは");
  return (
    <>
      <Head>
        <title>Notion Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-3xl font-bold">Hello world!</h1>
    </>
  );
}
