import SinglePosts from "@/components/Posts/SinglePosts";
import { getAllPosts } from "@/lib/notionAPI";
// import { Post } from "@/types";
import Head from "next/head";

export const getStaticProps = async () => {
  const allPosts = await getAllPosts(); //notionAPI.tsxから関数呼び出し
  console.log("posts:", allPosts);
  return {
    props: {
      allPosts,
    },
    revalidate: 60 * 60,
  };
};

export default function Home({ allPosts }) {
  return (
    <div className="container h-full w-full mx-auto">
      <Head>
        <title>Notion Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container w-full mt-16">
        <h1 className="text-5xl font-medium mb-16 text-center">トップページです！</h1>
        {allPosts.map((post) => (
          <div className="mx-4" key={post.id}>
            <SinglePosts
              title={post.title}
              description={post.description}
              date={post.date}
              tags={post.tags}
              slug={post.slug}
            />
          </div>
        ))}
      </main>
    </div>
  );
}
