import Pagination from "@/components/Pagination";
import SinglePosts from "@/components/Posts/SinglePosts";
import TagSearch from "@/components/TagSearch";
import {
  getAllTags,
  getNumberOfPagesByTag,
  getPostsByTag,
} from "@/lib/notionAPI";
import { GetStaticPaths, GetStaticProps } from "next";
import Head from "next/head";

export const getStaticPaths: GetStaticPaths = async () => {
  const allTags = await getAllTags(); //NotionAPIから全てのタグを取得した関数を呼び出す
  let params = [];

  //非同期処理を並列に処理できるようにする
  await Promise.all(
    allTags.map((tag: string) => {
      return getNumberOfPagesByTag(tag).then((numberOfPageByTag: number) => {
        for (let i = 1; i <= numberOfPageByTag; i++) {
          params.push({ params: { tag: tag, page: i.toString() } });
        }
      });
    })
  );

  return {
    paths: params,
    fallback: "blocking",
  };
};

export const getStaticProps: GetStaticProps = async (context) => {
  const currentPage: string = context.params?.page.toString();
  const currentTag: string = context.params?.tag.toString();

  const upperCaseCurrentTag =
    currentTag.charAt(0).toUpperCase() + currentTag.slice(1);

  const posts = await getPostsByTag(
    upperCaseCurrentTag,
    parseInt(currentPage, 10)
  );

  const numberOfPagesByTag = await getNumberOfPagesByTag(upperCaseCurrentTag);
  const allTags = await getAllTags();

  return {
    props: {
      posts,
      numberOfPagesByTag,
      allTags,
    },
    revalidate: 60 * 60,
  };
};

const BlogTagPageList = ({ numberOfPagesByTag, posts, allTags }) => {
  return (
    <div className="container h-full w-full mx-auto">
      <Head>
        <title>Notion Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container w-full mt-16">
        <section>
          <h1 className="text-5xl font-medium mb-16 text-center">
            もっと見るページです！
          </h1>
          {posts.map((post) => (
            <div className="mx-4" key={post.id}>
              <SinglePosts
                title={post.title}
                description={post.description}
                date={post.date}
                tags={post.tags}
                slug={post.slug}
                isSeeMorePage={true}
              />
            </div>
          ))}
        </section>
        <Pagination numberOfPage={numberOfPagesByTag} tag={""} />
        <TagSearch tags={allTags} />
      </main>
    </div>
  );
};

export default BlogTagPageList;
